small advances

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -1,10 +1,10 @@
 
 # enable color support of ls and also add handy aliases
 if [ -x /usr/bin/dircolors ]; then
-    alias ls='ls --color=auto'
-    alias grep='grep --color=auto'
-    alias fgrep='fgrep --color=auto'
-    alias egrep='egrep --color=auto'
+  alias ls='ls --color=auto'
+  alias grep='grep --color=auto'
+  alias fgrep='fgrep --color=auto'
+  alias egrep='egrep --color=auto'
 fi
 
 # some more ls aliases
@@ -55,70 +55,100 @@ alias dm='dmenu_run -nb "#602B00" -nf "#6df4f4" -sb "#FF0000" -b -p dmenu:'
 ##################
 
 # show all colors on terminal
-sh-colors(){
-for i in {1..255}; do echo -e "\e[38;5;${1};1m\e[48;5;${i}m    \e[0m\e[38;5;${i}m $i\e[0m"; done
+sh_colors(){
+  for i in {1..255}; do echo -e "\e[38;5;${1};1m\e[48;5;${i}m    \e[0m\e[38;5;${i}m $i\e[0m"; done
 }
 
 # clean latex files
 cleantex(){
-RMFILES=$(ls *.aux *.bbl *.blg *.out *.log *.dvi *.toc 2>>/dev/null)
-if [ "$RMFILES" == "" ];
-then
-  echo "Folder already clean, bye."
-  exit 0
-else
-  echo $RMFILES
-  read -p 'Do you want me to swip out those files??? [Y/n]'
-  [ "$REPLY" == "y" ] && rm $RMFILES || echo "OK, bye!"
-fi
+  RMFILES=$(ls *.aux *.bbl *.blg *.out *.log *.dvi *.toc 2>>/dev/null)
+  if [ "$RMFILES" == "" ];
+  then
+    echo "Folder already clean, bye."
+    exit 0
+  else
+    echo $RMFILES
+    read -p 'Do you want me to swip out those files??? [Y/n]'
+    [ "$REPLY" == "y" ] && rm $RMFILES || echo "OK, bye!"
+  fi
 }
 
 # Multiple skypes
 skp(){
-PROGNAME=$FUNCNAME
-USER=$1
-if [[ "$USER" == mauro || "$USER" == cinghio ]];
-then
-  DBDIR=~/.config/Skype-$USER
-  skype --dbpath=$DBDIR
-else
-  echo $PROGNAME: user $USER unknown 1>&2
-  echo Usage: $PROGNAME username
-  echo username = mauro / cinghio
-#  exit 1
-fi
+  PROGNAME=$FUNCNAME
+  USER=$1
+  if [[ "$USER" == mauro || "$USER" == cinghio ]];
+  then
+    DBDIR=~/.config/Skype-$USER
+    skype --dbpath=$DBDIR
+  else
+    echo $PROGNAME: user $USER unknown 1>&2
+    echo Usage: $PROGNAME username
+    echo username = mauro / cinghio
+  #  exit 1
+  fi
 }
 
 # git remove submodules
 rm_git_submodules(){
-submodulepath=${1%/}
-git rm --cached $submodulepath
-git config -f .git/config --remove-section submodule.$submodulepath
-git config -f .gitmodules --remove-section submodule.$submodulepath
-rm -Rf .git/modules/$submodulepath
-rm -Rf $submodulepath
+  submodulepath=${1%/}
+  git rm --cached $submodulepath
+  git config -f .git/config --remove-section submodule.$submodulepath
+  git config -f .gitmodules --remove-section submodule.$submodulepath
+  rm -Rf .git/modules/$submodulepath
+  rm -Rf $submodulepath
 }
 
 # vimwiki custom conversion to html
 custom_md2html (){
-# This script converts markdown into html, to be used with vimwiki's
-# "customwiki2html" option. Experiment with the two proposed methods by
-# commenting / uncommenting the relevant lines below.
-# Then, in your .vimrc file, set:
-#
-# g:vimwiki_customwiki2html=$HOME.'/.vim/autoload/vimwiki/customwiki2html.sh'
-PANDOC=pandoc
+  # This script converts markdown into html, to be used with vimwiki's
+  # "customwiki2html" option. Experiment with the two proposed methods by
+  # commenting / uncommenting the relevant lines below.
+  # Then, in your .vimrc file, set:
+  #
+  # g:vimwiki_customwiki2html=$HOME.'/.vim/autoload/vimwiki/customwiki2html.sh'
+  PANDOC=pandoc
 
-FORCE="$1"
-SYNTAX="$2"
-EXTENSION="$3"
-OUTPUTDIR="$4"
-INPUT="$5"
-CSSFILE="$6"
+  FORCE="$1"
+  SYNTAX="$2"
+  EXTENSION="$3"
+  OUTPUTDIR="$4"
+  INPUT="$5"
+  CSSFILE="$6"
 
-[ $FORCE -eq 0 ] || { FORCEFLAG="-f"; };
-[ $SYNTAX = "markdown" ] || { echo "Error: Unsupported syntax"; exit -2; };
+  [ $FORCE -eq 0 ] || { FORCEFLAG="-f"; };
+  [ $SYNTAX = "markdown" ] || { echo "Error: Unsupported syntax"; exit -2; };
 
-OUTPUT=$OUTPUTDIR/$(basename "$INPUT" .$EXTENSION).html
-$PANDOC --css $CSSFILE --mathjax -o $OUTPUT $INPUT
+  OUTPUT=$OUTPUTDIR/$(basename "$INPUT" .$EXTENSION).html
+  $PANDOC --css $CSSFILE --mathjax -o $OUTPUT $INPUT
 }
+
+vcs(){
+#  #get infos about vesrioning systems
+  while [[ ! -d .git && ! -d .svn && ! `pwd` = "/" ]]; do cd ..; done
+  if [[ -d .git ]];
+  then
+    BRANCH=$(awk -F'/' '{print $NF}' .git/HEAD)
+    echo "[git]-"$BRANCH
+  elif [[ -d .svn ]];
+  then 
+    echo "[svn]"
+  fi
+}
+
+pdf_booklet (){
+  #convert pdf to a booklet format to be printable
+  # usage: pdf_booklet infile.pdf outfile.pdf
+  # print to a4 papersize.
+  INFILE="$1"
+  OUTFILE="$2"
+  PAPER=$(pdfinfo $INFILE | grep 'Page size' | sed 's/.*(\(.*\)).*/\1/' | tr '[A-Z]' '[a-z]')
+  pdftops -level3 $INFILE - |\
+    ps2ps - - |\
+    psbook |\
+    psnup -2 -pa4 -P$PAPER |\
+    ps2pdf - $OUTFILE
+}
+
+# vim: set ft=sh:
+# vim: set fdm=indent:
